// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/tryout": {
    params: {};
  };
  "/login": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/dashboard" | "/register" | "/tryout" | "/login";
  };
  "routes/_page.dashboard.tsx": {
    id: "routes/_page.dashboard";
    page: "/dashboard";
  };
  "routes/_page.register.tsx": {
    id: "routes/_page.register";
    page: "/register";
  };
  "routes/_page._index.tsx": {
    id: "routes/_page._index";
    page: "/";
  };
  "routes/_page.tryout.tsx": {
    id: "routes/_page.tryout";
    page: "/tryout";
  };
  "routes/_page.login.tsx": {
    id: "routes/_page.login";
    page: "/login";
  };
};