// import { TryoutDetail } from "./interface";

// // Standard 7 subtests for all tryouts
// const standardCategories = [
//   {
//     id: 1,
//     name: "Penalaran Umum",
//     questionCount: 30,
//     duration: 30,
//     isCompleted: false,
//   },
//   {
//     id: 2,
//     name: "Pengetahuan dan Pemahaman Umum",
//     questionCount: 20,
//     duration: 15,
//     isCompleted: false,
//   },
//   {
//     id: 3,
//     name: "Kemampuan Memahami Bacaan dan Menulis",
//     questionCount: 20,
//     duration: 25,
//     isCompleted: false,
//   },
//   {
//     id: 4,
//     name: "Pengetahuan Kuantitatif",
//     questionCount: 20,
//     duration: 20,
//     isCompleted: false,
//   },
//   {
//     id: 5,
//     name: "Literasi dalam Bahasa Indonesia",
//     questionCount: 30,
//     duration: 43,
//     isCompleted: false,
//   },
//   {
//     id: 6,
//     name: "Literasi dalam Bahasa Inggris",
//     questionCount: 20,
//     duration: 20,
//     isCompleted: false,
//   },
//   {
//     id: 7,
//     name: "Penalaran Matematika",
//     questionCount: 20,
//     duration: 43,
//     isCompleted: false,
//   },
// ];

// // Completed categories for testing (for tryout #2)
// const completedCategories = [
//   {
//     id: 1,
//     name: "Penalaran Umum",
//     questionCount: 30,
//     duration: 30,
//     isCompleted: true,
//   },
//   {
//     id: 2,
//     name: "Pengetahuan dan Pemahaman Umum",
//     questionCount: 20,
//     duration: 15,
//     isCompleted: true,
//   },
//   {
//     id: 3,
//     name: "Kemampuan Memahami Bacaan dan Menulis",
//     questionCount: 20,
//     duration: 25,
//     isCompleted: false,
//   },
//   {
//     id: 4,
//     name: "Pengetahuan Kuantitatif",
//     questionCount: 20,
//     duration: 20,
//     isCompleted: false,
//   },
//   {
//     id: 5,
//     name: "Literasi dalam Bahasa Indonesia",
//     questionCount: 30,
//     duration: 43,
//     isCompleted: false,
//   },
//   {
//     id: 6,
//     name: "Literasi dalam Bahasa Inggris",
//     questionCount: 20,
//     duration: 20,
//     isCompleted: false,
//   },
//   {
//     id: 7,
//     name: "Penalaran Matematika",
//     questionCount: 20,
//     duration: 43,
//     isCompleted: false,
//   },
// ];

// export const tryoutDetails: { [key: number]: TryoutDetail } = {
//   1: {
//     id: 1,
//     title: "Try Out UTBK SNBT 4 2026",
//     number: "4",
//     badge: "SNBT",
//     participants: 375,
//     description:
//       "Try Out UTBK SNBT 4 2026 adalah simulasi lengkap ujian SNBT yang dirancang untuk mempersiapkan kamu menghadapi ujian sesungguhnya. Dengan soal-soal yang sesuai dengan kisi-kisi terbaru dan sistem penilaian yang akurat.",
//     duration: 195,
//     totalQuestions: 150,
//     startDate: "2026-01-15",
//     endDate: "2026-02-28",
//     isRegistered: false,
//     isFree: false,
//     tokenCost: 1,
//     categories: standardCategories,
//     benefits: [
//       "Pembahasan lengkap untuk setiap soal",
//       "Analisis mendalam terhadap hasil try out",
//       "Perbandingan dengan peserta lain secara nasional",
//       "Rekomendasi materi yang perlu dipelajari",
//       "Sertifikat digital setelah mengerjakan",
//       "Akses rekaman video pembahasan",
//     ],
//     requirements: [
//       "1 Token Try Out (bisa dibeli di halaman Shop)",
//       "Koneksi internet yang stabil",
//       "Perangkat laptop/PC untuk pengalaman terbaik",
//       "Waktu luang 195 menit tanpa gangguan",
//     ],
//   },
//   2: {
//     id: 2,
//     title: "Try Out UTBK SNBT 3 2026",
//     number: "3",
//     badge: "SNBT",
//     participants: 18048,
//     description:
//       "Try Out UTBK SNBT 3 2026 memberikan pengalaman try out yang komprehensif dengan soal-soal berkualitas dan sistem penilaian yang akurat untuk mengukur kemampuan kamu.",
//     duration: 195,
//     totalQuestions: 150,
//     startDate: "2025-12-01",
//     endDate: "2026-01-31",
//     isRegistered: true,
//     isFree: false,
//     tokenCost: 1,
//     categories: completedCategories,
//     benefits: [
//       "Pembahasan lengkap untuk setiap soal",
//       "Analisis mendalam terhadap hasil try out",
//       "Perbandingan dengan peserta lain secara nasional",
//       "Rekomendasi materi yang perlu dipelajari",
//       "Sertifikat digital setelah mengerjakan",
//       "Akses rekaman video pembahasan",
//     ],
//     requirements: [
//       "1 Token Try Out (bisa dibeli di halaman Shop)",
//       "Koneksi internet yang stabil",
//       "Perangkat laptop/PC untuk pengalaman terbaik",
//       "Waktu luang 195 menit tanpa gangguan",
//     ],
//   },
//   3: {
//     id: 3,
//     title: "Try Out UTBK SNBT 2 2026",
//     number: "2",
//     badge: "SNBT",
//     participants: 21712,
//     description:
//       "Try Out UTBK SNBT 2 2026 hadir dengan soal-soal yang dirancang oleh tim ahli untuk membantu kamu mempersiapkan diri menghadapi UTBK SNBT dengan lebih percaya diri.",
//     duration: 195,
//     totalQuestions: 150,
//     startDate: "2025-11-01",
//     endDate: "2025-12-31",
//     isRegistered: false,
//     isFree: true,
//     categories: standardCategories,
//     benefits: [
//       "Pembahasan lengkap untuk setiap soal",
//       "Analisis mendalam terhadap hasil try out",
//       "Perbandingan dengan peserta lain secara nasional",
//       "Rekomendasi materi yang perlu dipelajari",
//       "Sertifikat digital setelah mengerjakan",
//     ],
//     requirements: [
//       "Gratis! Tidak perlu token",
//       "Koneksi internet yang stabil",
//       "Perangkat laptop/PC untuk pengalaman terbaik",
//       "Waktu luang 195 menit tanpa gangguan",
//     ],
//   },
//   4: {
//     id: 4,
//     title: "Try Out UTBK SNBT 1 2026",
//     number: "1",
//     badge: "SNBT",
//     participants: 30229,
//     description:
//       "Try Out UTBK SNBT 1 2026 adalah try out perdana untuk tahun 2026 dengan soal-soal yang telah disesuaikan dengan format terbaru UTBK SNBT.",
//     duration: 195,
//     totalQuestions: 150,
//     startDate: "2025-10-01",
//     endDate: "2025-11-30",
//     isRegistered: true,
//     isFree: true,
//     categories: standardCategories,
//     benefits: [
//       "Pembahasan lengkap untuk setiap soal",
//       "Analisis mendalam terhadap hasil try out",
//       "Perbandingan dengan peserta lain secara nasional",
//       "Rekomendasi materi yang perlu dipelajari",
//       "Sertifikat digital setelah mengerjakan",
//     ],
//     requirements: [
//       "Gratis! Tidak perlu token",
//       "Koneksi internet yang stabil",
//       "Perangkat laptop/PC untuk pengalaman terbaik",
//       "Waktu luang 195 menit tanpa gangguan",
//     ],
//   },
//   5: {
//     id: 5,
//     title: "Try Out UTBK SNBT 14 2025",
//     number: "14",
//     badge: "SNBT",
//     participants: 188475,
//     description:
//       "Try Out UTBK SNBT 14 2025 adalah try out dengan jumlah peserta terbanyak! Ujian ini memberikan pengalaman kompetisi yang sesungguhnya dengan ribuan peserta dari seluruh Indonesia.",
//     duration: 195,
//     totalQuestions: 150,
//     startDate: "2025-09-01",
//     endDate: "2025-10-31",
//     isRegistered: false,
//     isFree: false,
//     tokenCost: 1,
//     categories: standardCategories,
//     benefits: [
//       "Pembahasan lengkap untuk setiap soal",
//       "Analisis mendalam terhadap hasil try out",
//       "Perbandingan dengan peserta lain secara nasional",
//       "Rekomendasi materi yang perlu dipelajari",
//       "Sertifikat digital setelah mengerjakan",
//       "Akses rekaman video pembahasan",
//     ],
//     requirements: [
//       "1 Token Try Out (bisa dibeli di halaman Shop)",
//       "Koneksi internet yang stabil",
//       "Perangkat laptop/PC untuk pengalaman terbaik",
//       "Waktu luang 195 menit tanpa gangguan",
//     ],
//   },
//   6: {
//     id: 6,
//     title: "Try Out UTBK SNBT 13 2025",
//     number: "13",
//     badge: "SNBT",
//     participants: 156521,
//     description:
//       "Try Out UTBK SNBT 13 2025 menghadirkan soal-soal terkini yang telah disesuaikan dengan kisi-kisi UTBK SNBT terbaru untuk membantu persiapan kamu.",
//     duration: 195,
//     totalQuestions: 150,
//     startDate: "2025-08-01",
//     endDate: "2025-09-30",
//     isRegistered: false,
//     isFree: false,
//     tokenCost: 1,
//     categories: standardCategories,
//     benefits: [
//       "Pembahasan lengkap untuk setiap soal",
//       "Analisis mendalam terhadap hasil try out",
//       "Perbandingan dengan peserta lain secara nasional",
//       "Rekomendasi materi yang perlu dipelajari",
//       "Sertifikat digital setelah mengerjakan",
//       "Akses rekaman video pembahasan",
//     ],
//     requirements: [
//       "1 Token Try Out (bisa dibeli di halaman Shop)",
//       "Koneksi internet yang stabil",
//       "Perangkat laptop/PC untuk pengalaman terbaik",
//       "Waktu luang 195 menit tanpa gangguan",
//     ],
//   },
// };

// export const getTryoutDetail = (id: number): TryoutDetail | undefined => {
//   return tryoutDetails[id];
// };
